{% set name = "notolog" %}
{% set version = "1.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/notolog-{{ version }}.tar.gz
  sha256: 140607eedb37c972fb0fd1f4178eb36f7dcd8464dfc13b009e9f44ac5fdf5070

build:
  entry_points:
    - notolog=notolog.app:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.5.0
  run:
    - python >={{ python_min }},<3.14
    - cffi >=1.17.1
    - click >=8.1.7
    - cryptography >=43.0.1
    - emoji >=2.14.0
    - iniconfig >=2.0.0
    - Markdown >=3.7
    - packaging >=24.0
    - pluggy >=1.5.0
    - pycparser >=2.22
    - Pygments >=2.18.0
    - PySide6 >=6.8.0.2
    - qasync >=0.27.1
    - tomli >=2.0.1
    - tomli-w >=1.0.0
    - typing_extensions >=4.12.0
    - llama-cpp-python >=0.2.90

test:
  imports:
    - notolog
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-mock
    - pyside6
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pytest tests/test_pkg_integration.py
    # Package requirements on PyPI differ slightly from those on conda-forge.
    #- pip check

app:
  entry: notolog
  icon: notolog-logo.png
  summary: Notolog - Python Markdown Editor

about:
  home: https://notolog.com
  summary: Notolog - Python Markdown Editor
  description: |
    Notolog is an open-source Markdown editor built with Python and PySide6, featuring AI-powered assistance and local-first privacy.
  dev_url: https://github.com/notolog/notolog-editor/
  doc_url: https://notolog.app
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - notolog
